### ISSUE TITLE
SVG Bug (XML declaration causes wrong MIME type)

### ISSUE THREAD

**Issue by qivox** [payloadcms/plugin-cloud-storage#11]
Hey Payload Team,

When uploading SVG images, the Azure adapter creates an .xml (application/xml) file instead of a .svg (image/svg+xml) file.

**Comment by jmikrut** [comment]
Hey @qivox - what version are you on? We fixed this already 👍

**Comment by qivox** [comment]
> Hey @qivox - what version are you on? We fixed this already 👍

Hey @jmikrut – I'm on 1.0.8

**Comment by qivox** [comment]
Alright, the issue was actually because the SVG file contained the typical

`<?xml version="1.0" encoding="UTF-8"?>`

at the top which results in it receiving the XML definitions despite being an SVG file. Removing the XML header fixes the issue.

**Comment by klapec** [comment]
I wonder if this is correct though? It's typical for a .svg file to contain the `<?xml` tag on top of it, it renders correctly as a vector image - why would payload assume it's an `application/xml` instead of `image/svg+xml`?

**Comment by qivox** [comment]
> It's typical for a .svg file to contain the `<?xml` tag on top of it

I have to agree. Especially having every major UI tool automatically adding the XML declaration. Manually having to remove it is a pain. Even worse explaining the issue to non-technical people. I am reopening this issue due to this.

**Comment by jmikrut** [comment]
I agree with all of this. We will be pushing a fix here shortly. Good stuff, everyone, and thank you for the input!

**Comment by jmikrut** [comment]
Hey @qivox — can you try this again with the newest version of Payload? This may have been a Payload bug and not a `plugin-cloud-storage` bug. Let me know if the issue persists.
