### ISSUE TITLE
Cloudinary Adapter/Plugin? (Question, not an issue)

### ISSUE THREAD

**Issue by BayBreezy** [payloadcms/plugin-cloud-storage#15]
Hey,

I was just wondering if there is any plan to create an adapter for Cloudinary?
If not, is there like a guide that I could try following to create such a package/plugin?

**Comment by afzaalahmad** [comment]
@BayBreezy you can write your custom adapter by following the same pattern of current adapters. I'll see if I can add an adapter for cloudinary soon.

**Comment by jmikrut** [comment]
Hey @BayBreezy - yep, this would be totally possible. It's fairly straightforward to add your own adapters as well, and we would happily support an internal Cloudinary adapter right within this plugin if that seems appropriate to you.

@afzaalahmad I really really appreciate your help around here. You have been amazing.

**Comment by jmikrut** [comment]
Hey all, just trying to keep up with issues in this repo a bit today and I will close this one as it's not an issue per-se. Of course we would still certainly entertain a Cloudinary adapter for sure!

**Comment by denolfe** [comment]
This might be worth looking at as an alternative https://github.com/finkinfridom/payload-cloudinary-plugin
