### ISSUE TITLE
Headers from S3 not mantained when requesting assets from CMS

### ISSUE THREAD

**Issue by AlexPagnotta** [payloadcms/plugin-cloud-storage#18]
Hello,

I'm using this plugin with the s3 adapter, and I noticed that when an asset is requested from the CMS, all the headers normally returned from S3 are stripped, for example when requesting a video file, we don't get the "Content-Type", "Accept-Ranges" etc. headers that are instead present when requesting the same asset directly from AWS.

I can easily avoid this problem by requesting the assets using the S3 url directly, but I wanted to be sure that is the expected behaviour and I'm not missing anything.

**Comment by AlexPagnotta** [comment]
Hi @jmikrut, just added a PR https://github.com/payloadcms/plugin-cloud-storage/pull/21.
As I wrote on the PR description, I've added the header to S3 and Azure, but I couldn't find the header on GCS metadata object, it seems that is not returned at all, so I am not sure if we should handle it somehow or just skip it.

**Comment by jmikrut** [comment]
Hey @AlexPagnotta — this was just merged. Again, thank you for the PR and your patience!
