### ISSUE TITLE
plugin-cloud-storage or payload-s3-upload?

### ISSUE THREAD

**Issue by toinelin** [payloadcms/plugin-cloud-storage#3]
Hi PayloadCMS team!

I'm a bit confused about which plugin we should use for handling uploads to S3, this one looks more "fresh" and maintained compared to the other one, but the other looks to have more available options. Am I wrong?

Thank you for the great work, I'm loving PayloadCMS so far 🙏🏻

**Comment by jmikrut** [comment]
Hey @toinelin — welcome! Happy to hear you're enjoying Payload!

You should use this plugin. I don't know that the other plugin has anything more than this one does actually. Are you seeing features in specific that are missing from this plugin?
