### ISSUE TITLE
Support to Cloudflare R2 

### ISSUE THREAD

**Issue by FrancocDev** [payloadcms/plugin-cloud-storage#31]
Hi, i'm writing this issue to ask if there is any plan to include R2 buckets to this plugin due to all the features that it has like 10GB free quota, delivery on the edge so low latency and a good traffic quota that is way better than the other options. 
Also the free plan, would allow to deploy more payload projects to the average dev because with railway/render + mongodb atlas + R2 you can have a bulletproof PayloadCMS installation.
Thanks in advance and I hope this will be implemented.

**Comment by jaschaio** [comment]
@FrancocDev why did you immediately closed this as completed? Can you simply use the AWS s3 adapter? Or is there a cloudflare r2 adapter somwhere I have missed?

**Comment by JarrodMFlesch** [comment]
@jaschaio check out this test file, we have an R2 config here: https://github.com/payloadcms/payload/blob/main/test/plugin-cloud-storage/config.ts
