### ISSUE TITLE
Error while deleting file. The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by hgenru** [payloadcms/plugin-cloud-storage#34]
When using `imageSizes` (with sharp at least), "empty" resizes can be generated. It looks like this:

```
{
  "id": "63c5059799edb6faa80fcb7a",
  "filename": "activelearning.png",
  "mimeType": "image/png",
  "filesize": 12683,
  "width": 267,
  "height": 267,
  "sizes": {
    "small": {
      "width": 240,
      "height": 240,
      "mimeType": "image/webp",
      "filesize": 3438,
      "filename": "image.png",
      "url": "<url>"
    },
    "big": {
      "url": null,
      "width": null,
      "height": null,
      "mimeType": null,
      "filesize": null,
      "filename": null
    }
  },
  "createdAt": "2023-01-16T08:06:47.201Z",
  "updatedAt": "2023-01-16T08:06:47.201Z",
  "url": "<url>"
}
```

This happens when the size parameter is larger than the size of the original image. And on such files the deletion functionality breaks. Error looks like:
```
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
        at new NodeError (node:internal/errors:400:5)
        at validateString (node:internal/validators:163:11)
        at Object.join (node:path:1172:7)
        at C:\Users\me\Work\proj\node_modules\@payloadcms\plugin-cloud-storage\src\adapters\s3\handleDelete.ts:14:23
```

The error occurs [here](https://github.com/payloadcms/plugin-cloud-storage/blob/f333ff1c5bad9ef04124b04a9fd19edbdc7c0409/src/adapters/s3/handleDelete.ts#L14). To eliminate it, it is enough to add a check for null. If conceptually such changes do not interfere, then I can add them. But, most likely, the same problem occurs in other adapters, it may be worth repairing everything at once. True, I can hardly test other adapters normally.

**Comment by jmikrut** [comment]
Hey @hgenru thank you for the report! This is now fixed and will be released shortly. 😎
