### ISSUE TITLE
s3 adapter is not working with create-payload-app template

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/plugin-cloud-storage#38]
Repo for reproduction: https://github.com/MoSattler/fs-repro

Reproduction steps:

1. `npx create-payload-app fs-repro` - choose blank + typescript
1.  `yarn add @payloadcms/plugin-cloud-storage @aws-sdk/client-s3 @aws-sdk/lib-storage @aws-sdk/client-s3`
1. add S3 to payload config (see [here](https://github.com/MoSattler/fs-repro/commit/afff6c436d2402208595300e289d96c1e1258df7))
1. run `yarn build` 

output is:
```
Module not found: Error: Can't resolve 'fs' in '/Users/user/fs-repro/node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3'
```

**Comment by paulpopus** [comment]
In your reproduction repo, I don't see the plugin being added into the payload config?

You need a plugins key like this

```
collections: [],
plugins: [
    cloudStorage({
      collections: {
        media: {
          adapter: adapter,
        },
      },
    }),
    ```

**Comment by denolfe** [comment]
@MoSattler What version of Payload and plugin is being installed? I'm unable to recreate this. Only difference being, I used the blog template which has a media collection ready to go.

Do you have any other code being pulled in? That commit _added_ an additional alias for fs, so I wouldn't expect it to cause the issue you're seeing.

<img width="625" alt="CleanShot 2023-02-16 at 11 00 05" src="https://user-images.githubusercontent.com/65888/219420719-6f3eb687-12bf-41ec-b919-e0577d4282b8.png">

**Comment by paulpopus** [comment]
Yeah I just pulled this down and can reproduce. Weird cause I updated our project and didn't encounter it in the existing one.

**Comment by paulpopus** [comment]
@MoSattler @denolfe 

The issue seems related to a lack of a config and Media document being added, in this ^ repo which I could reproduce, I added a new Media collection and added it into the config and the issue went away:

```ts
import { buildConfig } from 'payload/config'
import path from 'path'
// import Examples from './collections/Examples';
import Users from './collections/Users'
import { Media } from './collections/Media'
import { cloudStorage } from '@payloadcms/plugin-cloud-storage'
import { s3Adapter } from '@payloadcms/plugin-cloud-storage/s3'

const doS3Adapter = s3Adapter({
  config: {
    endpoint: process.env.S3_ENDPOINT,
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY,
      secretAccessKey: process.env.S3_SECRET_KEY,
    },
  },
  bucket: process.env.S3_BUCKET,
})

export default buildConfig({
  serverURL: 'http://localhost:3009',
  admin: {
    user: Users.slug,
  },
  collections: [
    Users,
    Media,
    // Add Collections here
    // Examples,
  ],
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },
  plugins: [
    cloudStorage({
      collections: {
        media: {
          adapter: doS3Adapter,
        },
      },
    }),
  ],
})
```

**Comment by denolfe** [comment]
All good, just for some additional context - a plugin's webpack aliasing will only be applied if it is present in the plugins array of your config. So since you weren't including the plugin in the config, only instantiating it, the webpack aliasing for `fs` wasn't being applied.
