### ISSUE TITLE
Newly uploaded files not found

### ISSUE THREAD

**Issue by xlukasfrana** [payloadcms/plugin-cloud-storage#41]
I am using S3 storage from DigitalOcean. However, when I updated Payload and this plugin to the newest version, I cannot access new files. The old ones are to be found, but the newly created throws 404. I can see the files in the bucket.

**Comment by tylandavis** [comment]
Hey @xlukasfrana, I was running into this issue as well, fixed it by setting ACL permissions in my S3 adapter to public-read:
```javascript
const adapter = s3Adapter({
  config: {
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    },
    region: process.env.S3_REGION,
    endpoint: process.env.S3_ENDPOINT,
  },
  bucket: process.env.S3_BUCKET,
  acl: 'public-read',
});
```

**Comment by jmikrut** [comment]
Hey @xlukasfrana - yes, I think that Tylan's answer here is likely your issue. 

Please let us know if that resolves this. If it does not, then feel free to reopen the issue!
