### ISSUE TITLE
Conditionally running plugin causes webpack aliasing issue

### ISSUE THREAD

**Issue by denolfe** [payloadcms/plugin-cloud-storage#54]
If a payload config conditionally disables adding the plugin to the plugins array, webpack will throw an error on `fs`. This is because the webpack aliasing _should always run regardless of if the plugin is in use or not._.

In the following example, if the env var `S3_ENDPOINT` is not set, the plugin is not added to the plugins array, and therefore the plugin's webpack aliasing is not run. When building, an error will occur.

```
const plugins: Plugin[] = []

if (process.env.S3_ENDPOINT) {
  const adapter = s3Adapter({
    config: {
      endpoint: process.env.S3_ENDPOINT,
      forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
      region: process.env.S3_REGION,
      credentials: {
        accessKeyId: process.env.S3_ACCESS_KEY_ID,
        secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
      },
    },
    bucket: process.env.S3_BUCKET,
  })
  cloudStorage({
    collections: {
      media: {
        adapter,
      },
    },
  })
}

export default buildConfig({
  admin: {
    user: Users.slug,
  },
  collections: [Categories, Posts, Tags, Users, Media],
  plugins,
})
```

This is a very common use case. We need to come up with a pattern of how to handle this. 

One option:

- Add an `enabled` boolean to the plugin options. Inside the plugin, the resolved value can be evaluated, and the webpack aliasing can _always be run_. An example of this flow happens in [plugin-cloud](https://github.com/payloadcms/plugin-cloud/blob/main/src/plugin.ts#L12)

**Comment by denolfe** [comment]
With 1.0.17, you can now conditionally set an `enabled` boolean option on the plugin. Give that a try and let me know if you have any issues.

**Comment by ssyberg** [comment]
I'm still seeing this error even with a conditional `enabled`

```
cloudStorage({
            enabled: process.env.NODE_ENV === 'production',
            collections: {
                files: {
                    adapter: process.env.NODE_ENV === 'production' ? storageAdapter : null,
                    prefix: 'files',
                },
...
```

**Comment by ssyberg** [comment]
@denolfe even the conditional plugin creation isn't working for me oddly...

**Comment by denolfe** [comment]
@ssyberg Interesting, I tested this rather thoroughly and others verified the fix.

Can you paste more of your config? Can you confirm that `files` is the proper slug for your collection? (Others ran into that gotcha).

**Comment by ssyberg** [comment]
It looks like its the s3 adapter that's giving me trouble, not the plugin:
```
[nodemon] restarting due to changes...
[nodemon] starting `ts-node src/server.ts`
Debugger listening on ws://127.0.0.1:58446/c43f3a0b-25a1-48a1-9d8a-903bbac4328e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[21:06:52] INFO (payload): Connected to MongoDB server successfully!
[21:06:52] INFO (payload): Starting Payload...
[21:06:56] INFO (payload): Payload Admin URL: http://localhost:3000/cms/admin
webpack built 16ec1c4d470b092ef377 in 1789ms
ERROR in ./node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js 43:27-40
Module not found: Error: Can't resolve 'fs' in '/Users/seth/dev/carnegie/backend/node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3'
```

**Comment by ssyberg** [comment]
@denolfe confirmed it's otherwise working and writing to s3 perfectly! It's just for local dev that it's broken

**Comment by ssyberg** [comment]
More evidence the s3Adapter itself needs a similar "enabled" treatment (or inherit it somehow?)

```
        cloudStorage({
            enabled: false,
            collections: {
                files: {
                    adapter: true ? null : s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET }),
                    prefix: 'files',
                },
                images: {
                    adapter: true ? null : s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET || '' }),
                    prefix: 'media/images',
                },
                avatars: {
                    adapter: true ? null : s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET || '' }),
                    prefix: 'media/avatars',
                },
                videoPosters: {
                    adapter: true ? null : s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET || '' }),
                    prefix: 'media/video-posters',
                },
            },
        }),
```

Same error as above

**Comment by denolfe** [comment]
The idea is to evaluate the condition on the `enabled` property.  This is how it should be used.

Do you have a use case for conditionally enabling adapters?

```ts
cloudStorage({
    enabled: Boolean(process.env.S3_ASSETS_BUCKET)
    collections: {
        files: {
            adapter: s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET }),
            prefix: 'files',
        },
        images: {
            adapter: s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET })),
            prefix: 'media/images',
        },
        avatars: {
            adapter: s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET }),
            prefix: 'media/avatars',
        },
        videoPosters: {
            adapter: s3Adapter({ bucket: process.env.S3_ASSETS_BUCKET }),
            prefix: 'media/video-posters',
        },
    },
}),
```

**Comment by ssyberg** [comment]
> The idea is to evaluate the condition on the enabled property. This is how it should be used.

I'm not sure I'm following, I set it explicitly to `false` just to show that disabling it doesn't address the error.

> Do you have a use case for conditionally enabling adapters?

Only in that if I'm not using cloudStorage, I don't have any use for the adapters. I tried wrapping the s3adapter instantiation in a conditional as well but it didn't help here.

**Comment by denolfe** [comment]
Interesting. I'm not able to recreate your issue.

**Comment by ssyberg** [comment]
I may have narrowed this down a bit, thought this sure doesn't seem like it should fix it, it now builds fine:
```
cloudStorage({
            enabled: Boolean(process.env.S3_ASSETS_BUCKET),
            collections: {
                files: {
                    adapter: s3Adapter({ config: { endpoint: 'foo' }, bucket: process.env.S3_ASSETS_BUCKET }),
                    prefix: 'files',
                },
                images: {
                    adapter: s3Adapter({ config: { endpoint: 'foo' }, bucket: process.env.S3_ASSETS_BUCKET }),
                    prefix: 'media/images',
                },
                avatars: {
                    adapter: s3Adapter({ config: { endpoint: 'foo' }, bucket: process.env.S3_ASSETS_BUCKET }),
                    prefix: 'media/avatars',
                },
                videoPosters: {
                    adapter: s3Adapter({ config: { endpoint: 'foo' }, bucket: process.env.S3_ASSETS_BUCKET }),
                    prefix: 'media/video-posters',
                },
            },
        }),
```

**Comment by ssyberg** [comment]
Ok so this is my workaround for the moment - something about not having that endpoint config set when the plugin is disabled still breaks stuff

```
const storageAdapterConfig = { bucket: process.env.S3_ASSETS_BUCKET };
if (process.env.NODE_ENV !== 'production') {
    storageAdapterConfig.config = { endpoint: 'dummy-endpoint' };
}
const storageAdapter = s3Adapter(storageAdapterConfig);

....

        cloudStorage({
            enabled: process.env.NODE_ENV === 'production',
            collections: {
                files: {
                    adapter: storageAdapter,
                    prefix: 'files',
                },
                images: {
                    adapter: storageAdapter,
                    prefix: 'media/images',
                },
                avatars: {
                    adapter: storageAdapter,
                    prefix: 'media/avatars',
                },
                videoPosters: {
                    adapter: storageAdapter,
                    prefix: 'media/video-posters',
                },
            },
        }),
```

**Comment by ssyberg** [comment]
Is it possible that this fix hasn't actually made it into the version I'm using? I'm fairly certain at this point that `enabled` isn't doing anything...

`"@payloadcms/plugin-cloud-storage": "^1.0.17",`

**Comment by denolfe** [comment]
This is just a type issue, nothing to do with webpack aliasing.

With your code, my IDE yells at me for a misconfigured `s3Adapter`.

<img width="1060" alt="CleanShot 2023-06-14 at 22 01 41@2x" src="https://github.com/payloadcms/plugin-cloud-storage/assets/65888/5d0e42d9-0cb7-4a46-abea-1959892e90e3">

**Comment by ssyberg** [comment]
Ok I think there were a bunch of conflating issues that ultimately hid the actual issue which is quite simple but is hinted at in the errors above. Essentially the issue seems to be with `config.endpoint`

This config works just fine in development, but it's broken in production because that endpoint is fake:
```
        cloudStorage({
            enabled: Boolean(process.env.S3_ASSETS_BUCKET),
            collections: {
                files: {
                    adapter: s3Adapter({
                        config: {
                            endpoint: 'dummy-endpoint',
                        },
                        bucket: process.env.S3_ASSETS_BUCKET,
                    }),
                    prefix: 'files',
                },
            },
        }),
```

Meanwhile THIS configuration works totally fine in `production` but breaks in `development` because (the non-required field) `config.endpoint` is missing.

```
        cloudStorage({
            enabled: Boolean(process.env.S3_ASSETS_BUCKET),
            collections: {
                files: {
                    adapter: s3Adapter({
                        bucket: process.env.S3_ASSETS_BUCKET,
                    }),
                    prefix: 'files',
                },
            },
        }),
```

I'm guessing the workaround here is to be unnecessarily explicit about the endpoint on production and treat it as required. Will try that and report back.

**Comment by ssyberg** [comment]
Sorry misspoke again, it's not about endpoint, it's just that `config` needs to be an object:

```
adapter: s3Adapter({
                        config: {},
                        bucket: process.env.S3_ASSETS_BUCKET,
                    }),
```

**Comment by ssyberg** [comment]
Still fighting with this actually, worth clarifying for my use case there are no credentials for accessing s3. This is for a deployment where payload is running in a AWS VPC and has an assigned IAM role to allow s3 write access. The above still is giving me errors in production on the endpoint not being set. I've verified that this is not a permissions issue as I can write to the s3 bucket from the production server via cmd line/script.

**Comment by denolfe** [comment]
@ssyberg Can you write this up in a new issue? Definitely separate from the original issue.

**Comment by ssyberg** [comment]
Yup was about to suggest the same!
