### ISSUE TITLE
ERROR (payload): Region is missing

### ISSUE THREAD

**Issue by SynthLuvr** [payloadcms/plugin-cloud-storage#56]
I'm using:

``` typescript
  plugins: [
    cloudStorage({
      collections: {
        media: {
          adapter: s3Adapter({
            config: {
              credentials: {
                accessKeyId: process.env.S3_ACCESS_KEY_ID,
                secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
              },
              endpoint: process.env.S3_ENDPOINT,
            },
            bucket: process.env.S3_BUCKET,
          }),
        },
      },
    }),
  ],
```

When I try to interact with media, it fails to upload and retrieve items, instead showing error that region is missing:

```
ERROR (payload): Region is missing
    Error: Region is missing
```

**Comment by SynthLuvr** [comment]
Setting `region` under `config` resolved the error. Now I'm facing a new error:

```
ERROR (NoSuchKey): UnknownError
    NoSuchKey: UnknownError
```

**Comment by SynthLuvr** [comment]
> Setting `region` under `config` resolved the error. Now I'm facing a new error:
> 
> ```
> ERROR (NoSuchKey): UnknownError
>     NoSuchKey: UnknownError
> ```

Ok, got it working. I think just some improvements to the README will suffice.

Region needs to be set but it's missing from the README. The endpoint needs to include "https". If there are any files that failed to upload then it'll cause `NoSuchKey` errors.

**Comment by denolfe** [comment]
Hey @SynthLuvr, thank you for the detail. I'll add some of this to the readme.

**Comment by denolfe** [comment]
`endpoint` added to README.

I believe the endpoint property's docs are sufficient as it states "fully qualified", which means entire url including https/http.
