### ISSUE TITLE
Error when not providing s3 credentials (using Resource IAM Role based access)

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/plugin-cloud-storage#59]
I have AWS resources with assigned roles that allow s3 access so no access key credentials are required, but the s3 adapter doesn't allow this. 

Example config:

```
        cloudStorage({
            enabled: Boolean(process.env.S3_ASSETS_BUCKET),
            collections: {
                files: {
                    adapter: s3Adapter({
                        bucket: process.env.S3_ASSETS_BUCKET,
                    }),
                    prefix: 'files',
                },
            },
        }),
```

Error:
```
[15:27:53] ERROR (CredentialsProviderError): Could not load credentials from any providers
    CredentialsProviderError: Could not load credentials from any providers
        at /Users/seth/dev/***/backend/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
        at /Users/seth/dev/***/backend/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at coalesceProvider (/Users/seth/dev/***/backend/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
        at SignatureV4.credentialProvider (/Users/seth/dev/***/backend/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)
        at SignatureV4.signRequest (/Users/seth/dev/***/backend/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:106:29)
        at /Users/seth/dev/***/backend/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:16:18
        at /Users/seth/dev/***/backend/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
        at /Users/seth/dev/***/backend/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
        at /Users/seth/dev/***/backend/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

**Comment by denolfe** [comment]
Where is this running? How are you loading the role into the environment?

To me, if you're getting `ERROR (CredentialsProviderError): Could not load credentials from any providers`, it means the iam role isn't being loaded into the environment.

The `credentials` property is of the `AwsAuthInputConfig.credentials?: AwsCredentialIdentity | Provider<AwsCredentialIdentity>` type, which means you could provide a credentials provider that loads your IAM role. There are some examples [in the AWS Docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#table-of-contents) where you could likely find what you're looking for.

**Comment by ssyberg** [comment]
I'll answer this in two parts since I've run two different tests to confirm this, the results of which both support my hypothesis.

**On my production environment**
> Where is this running? How are you loading the role into the environment?

It's running on ECS - but it's a very common security pattern in our environments to not generate or use access keys if not absolutely necessary. Access keys can be leaked, resource roles/policies are relatively bullet proof.

> To me, if you're getting ERROR (CredentialsProviderError): Could not load credentials from any providers, it means the iam role isn't being loaded into the environment.

I've already tested for this, as I mentioned, I ssh'd into the container and successfully wrote to the bucket from the command line with no credentials. 

> that loads your IAM role

There's nothing to load, the AWS resource receives the role when the container is spun up. 

To further test this, I created a world writeable s3 bucket and confirmed I can write to this with no credentials of any kind, just using the aws-sdk and testing writing to that same bucket resulted in the error you see above. Here's the test script that I ran on both of the above experiments:

```
var AWS = require('aws-sdk');
var s3 = new AWS.S3();

var params = {
   Bucket: 'bucketName',
   Key: 'testfile.txt',
   Body: 'Hello!'
};

s3.putObject(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

**Comment by ssyberg** [comment]
Just mucking around in the transpiled node_modules I was able to fix this pretty easily, in `dist/adapters/s3/index.js`, line 34:

```
    var config = _a.config, bucket = _a.bucket, acl = _a.acl;
    if (!config) {
        config = {};
    }
```

**Comment by ssyberg** [comment]
I can PR this shortly
