### ISSUE TITLE
Source media not being resized

### ISSUE THREAD

**Issue by denolfe** [payloadcms/plugin-cloud-storage#78]
### Link to reproduction

.

### To Reproduce

- Configure payload with plugin-cloud-storage with a resize, and some other sizes
- Upload image
- Check the source media, it is not resized or compressed

### Describe the Bug

Source media not properly being resized on upload.

[Discord Thread](https://discord.com/channels/967097582721572934/1161691455052595200/1161974411876892742)

### Payload Version

2.0

### Adapters and Plugins

plugin-cloud-storage

**Comment by DennisSnijder** [comment]
@denolfe I'm getting a 500 error when trying to resize image when using the cloud plugin error on payload 2.0. It's due to my source image not being available on the local filesystem.

`ENOENT: no such file or directory, open '/home/node/app/media/maxresdefault.jpg'`

**Comment by denolfe** [comment]
> @denolfe I'm getting a 500 error when trying to resize image when using the cloud plugin error on payload 2.0. It's due to my source image not being available on the local filesystem.
> 
> `ENOENT: no such file or directory, open '/home/node/app/media/maxresdefault.jpg'`

@DennisSnijder I would guess that is an unrelated issue. Please open a separate one.

**Comment by denolfe** [comment]
This was fixed by https://github.com/payloadcms/payload/pull/3883 and https://github.com/payloadcms/payload/pull/3883 and https://github.com/payloadcms/payload/pull/3996. Released in 2.0.15. The fix was related to payload core.
