### ISSUE TITLE
Wrong Typescript type on disablePayloadAccessControl.

### ISSUE THREAD

**Issue by imphillipzissou** [payloadcms/plugin-cloud-storage#8]
Looks like the `disablePayloadAccessControl` option in the plugin-cloud-storage is set to `true` instead of `boolean`.

https://github.com/payloadcms/plugin-cloud-storage/blob/d318e2276c1e943c6242c29cfdc4741403ed8db0/src/types.ts#L55

Thanks!

**Comment by afzaalahmad** [comment]
@imphillipzissou you can use values as a types, and it is exactly what is implemented here.
For example, you might have seen something like this:

```
export type User = {
   role: 'admin' | 'user' | 'editor'
}
```
We are using values as a type indicating that role can only be one of those. Similarly, here `true` represent that the value of `disablePayloadAccessControl` can only be `true`, or you don't provide the variable at all.

**Comment by imphillipzissou** [comment]
oof. Thanks @afzaalahmad ! I had a feeling that was the case but local Typescript was complaining. Should have tried to reproduce before opening. Thanks again!
