### ISSUE TITLE
Resizing and/or updating focal points in 2.0 gives a 500 error.

### ISSUE THREAD

**Issue by DennisSnijder** [payloadcms/plugin-cloud-storage#81]
When using the `plugin-cloud-storage` plugin, resizing and/or updating a media's focal point gives a 500 error when using Payload 2.0.

Server console gives out the following output: `ENOENT: no such file or directory, open '/home/node/app/media/maxresdefault.jpg'`

**Comment by ssyberg** [comment]
Just wondering if this is planned to be addressed soon? Thx!

**Comment by JarrodMFlesch** [comment]
@ssyberg thanks for the ping! @JessChowdhury remind me tomorrow and we can merge your fix in 👍

**Comment by JarrodMFlesch** [comment]
@ssyberg the related PR has been merged into core. I believe it missed the release last week, so next version bump will include it.

**Comment by jamesvclements** [comment]
@JarrodMFlesch @jesschowdhury Unfortunately I'm still seeing a similar issue in 2.4.0 https://github.com/payloadcms/payload/issues/4422. It's no longer the "no such file", instead it's throwing a FileUploadError around line 81 of the `generateFileData` file so something is throwing inside here

```
  if (url && url.startsWith('/')) {
    const filePath = `${staticPath}/${filename}`
    const response = await getFileByPath(filePath)
    file = response as UploadedFile
    overwriteExistingFiles = true
  } else {
    const response = await getFileByURL(url)
    file = response as UploadedFile
    overwriteExistingFiles = true
  }
```
