### ISSUE TITLE
s3upload giving RangeError

### ISSUE THREAD

**Issue by krishnarastogi** [payloadcms/plugin-cloud-storage#9]
```
RangeError: Maximum call stack size exceeded
    at clone (/home/<user>/<folder>/node_modules/rfdc/index.js:37:18)
```
    
we are facing issue in deploying image upload to s3bucket,
do we need to configure the size limit or any other configuration to upload file directly to s3bucket.

**Comment by krishnarastogi** [comment]
@DanRibbens @jmikrut can you please suggest 
we are using node v18.8.0, will that be problem.

**Comment by krishnarastogi** [comment]
Hi @DanRibbens 

Thanks for your reply!

Have installed 
```
yarn add @aws-sdk/client-s3
yarn add @payloadcms/plugin-cloud-storage
```

Current version:
```
"@aws-sdk/client-s3": "^3.159.0",
"@payloadcms/plugin-cloud-storage": "^1.0.8",
```
Nodejs v18.8.0
Payload  v1.0.31

In payload.config.ts
```
import { cloudStorage } from '@payloadcms/plugin-cloud-storage';
import { s3Adapter } from '@payloadcms/plugin-cloud-storage/s3';
```

```
const adapter = s3Adapter({
  config: {
    endpoint: process.env.S3_ENDPOINT,
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    }
  },
  bucket: process.env.S3_BUCKET,
})
```
```
  plugins: [
    cloudStorage({
      collections: {
        'media': {
          adapter, 
        },
      },
    }),
  ],
```

after this 
https://github.com/payloadcms/plugin-cloud-storage/blob/master/dev/src/collections/Media.ts

Added Media.ts in the collection, and in plugin.config.ts 

after that we are getting below error in terminal

```
    at copyBuffer (/home/<user>/<folder>/node_modules/rfdc/index.js:6:19)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:56:17)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:58:17)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:58:17)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:58:17)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:58:17)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:58:17)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:58:17)
    at clone (/home/ubuntu/cms.r.web/node_modules/rfdc/index.js:58:17)
```

just guide us if we missed any step or which package version to use

**Comment by krishnarastogi** [comment]
Hi all, 

the trick was to pass forcePathStyle = true 

```
const adapter = s3Adapter({
  config: {
    forcePathStyle: true,
    endpoint: process.env.S3_ENDPOINT,
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    }
  },
  bucket: process.env.S3_BUCKET,
})
```

**Comment by DanieleDeLuis** [comment]
What if I don't want have path style URLs for my S3 objects? I doesn't seem a valid solution

**Comment by TatisLois** [comment]
This resolved the issue for me but i'm not 100% sure why or what's going on. Does anyone have the time to shed some light and should it be included in the readme?

**Comment by ktra99** [comment]
I got the same issue and I definitely think this should be looked into more throughly. I got a 404 response from the following link in the console - http://localhost:3000/api/media?locale=en&depth=0&fallback-locale=null

Could it be some kind of issue with the callback after the upload?

```
There was an error while uploading files corresponding to the collection media with filename 3.png:
[09:19:20] ERROR (payload): RangeError: Maximum call stack size exceeded
    at Function.from (node:buffer:301:28)
    at copyBuffer (/Users/user/Desktop/folder/node_modules/rfdc/index.js:6:19)
    at clone (/Users/user/Desktop/folder/node_modules/rfdc/index.js:56:17)
```

**Comment by krishnarastogi** [comment]
@ktra99 can you please install latest version of payload and @payloadcms/plugin-cloud-storage and try again.
